import { StyleSheet } from "react-native";

export const addPlantStyles = StyleSheet.create({
  container: { flex: 1, paddingTop: 10 },
  content: { padding: 20 },
  header: {
    fontSize: 28,
    marginTop: 5,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    textAlign: "center",
    opacity: 0.7,
    marginBottom: 24,
  },
  inputSection: {
    marginBottom: 20,
  },
  label: {
    marginBottom: 12,
    fontSize: 16,
    fontWeight: "600",
    flexDirection: "row",
    alignItems: "center",
  },
  photoAddButton: {
    marginBottom: 16,
  },
  photoContainer: {
    borderWidth: 2,
    borderColor: "#A0C878",
    borderStyle: "dashed",
    borderRadius: 12,
    padding: 32,
    alignItems: "center",
    backgroundColor: "#F8FDF6",
    marginTop: 8,
  },
  photoText: {
    fontSize: 16,
    fontWeight: "600",
    marginTop: 8,
    color: "#A0C878",
  },
  photoSubtext: {
    fontSize: 14,
    opacity: 0.7,
    marginTop: 4,
  },
  previewContainer: {
    position: "relative",
    marginBottom: 16,
  },
  preview: {
    width: "100%",
    height: 220,
    borderRadius: 16,
    marginTop: 12,
  },
  removePhotoBtn: {
    position: "absolute",
    top: 20,
    right: 8,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 20,
    padding: 4,
  },
  photoOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    opacity: 0,
  },
  changePhotoText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    marginTop: 4,
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    width: "85%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  modalButton: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  modalText: {
    fontSize: 18,
    textAlign: "center",
    fontWeight: "500",
  },
  input: {
    width: "100%",
    height: 52,
    borderColor: "#E0E0E0",
    borderWidth: 1.5,
    borderRadius: 12,
    paddingHorizontal: 16,
    backgroundColor: "#FAFAFA",
    fontSize: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
    paddingTop: 16,
  },
  saveButton: {
    width: "90%",
    marginBottom: 60,
    position: "absolute",
    bottom: 30,
    left: 20,
    right: 20,
  },
  // Not ekleme satırı
  noteInputRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 12,
  },
  addNoteBtn: {
    padding: 4,
  },
  // Notlar container
  notesContainer: {
    backgroundColor: "#F8FDF6",
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
  },
  // Eklenen notlar listesi
  noteItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
    justifyContent: "space-between",
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  noteContent: {
    flexDirection: "row",
    alignItems: "flex-start",
    flex: 1,
  },
  noteText: {
    fontSize: 15,
    flex: 1,
    lineHeight: 20,
  },
  removeNoteBtn: {
    padding: 4,
    marginLeft: 8,
  },

  // Tür önerileri stilleri
  speciesContainer: {
    position: "relative",
    zIndex: 1000,
  },
  suggestionsContainer: {
    position: "absolute",
    top: 54,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderWidth: 1.5,
    borderColor: "#E0E0E0",
    borderTopWidth: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    maxHeight: 200,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1001,
  },
  suggestionsList: {
    maxHeight: 200,
  },
  suggestionItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
    backgroundColor: "#fff",
  },
  suggestionText: {
    fontSize: 16,
    color: "#333",
    flex: 1,
  },

  // Sulama aralığı stilleri
  wateringInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  wateringInput: {
    flex: 1,
    textAlign: "center",
  },
  wateringUnit: {
    fontSize: 16,
    fontWeight: "600",
    color: "#666",
    paddingHorizontal: 12,
    paddingVertical: 16,
    backgroundColor: "#F8FDF6",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#E0E0E0",
    minWidth: 60,
    textAlign: "center",
  },
});
