import { StyleSheet } from "react-native";

export const chatStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  statusContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  statusCard: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderLeftWidth: 4,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  reconnectButton: {
    marginLeft: "auto",
    padding: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  statusText: {
    fontSize: 14,
    fontWeight: "600",
  },
  chatContainer: {
    flex: 1,
  },
  chatContent: {
    flex: 1,
    paddingHorizontal: 16,
  },
  chatHeader: {
    alignItems: "center",
    paddingVertical: 20,
    marginBottom: 10,
  },
  headerContent: {
    alignItems: "center",
    maxWidth: "85%",
  },
  headerIcon: {
    marginBottom: 8,
  },
  title: {
    fontSize: 26,
    marginBottom: 8,
    textAlign: "center",
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: 15,
    textAlign: "center",
    opacity: 0.8,
    lineHeight: 22,
    paddingHorizontal: 5,
  },
  messagesList: {
    flex: 1,
  },
  messagesContent: {
    paddingVertical: 8,
    flexGrow: 1,
  },
  emptyChat: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  welcomeAvatar: {
    width: 80,
    height: 80,
    marginBottom: 16,
    opacity: 0.8,
  },
  welcomeText: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 8,
  },
  welcomeSubtext: {
    fontSize: 14,
    textAlign: "center",
    opacity: 0.7,
  },
  messageContainer: {
    flexDirection: "row",
    marginVertical: 4,
    paddingHorizontal: 8,
  },
  userMessageContainer: {
    justifyContent: "flex-end",
  },
  assistantMessageContainer: {
    justifyContent: "flex-start",
  },
  assistantAvatar: {
    width: 32,
    height: 32,
    marginRight: 8,
    marginTop: 4,
  },
  userAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#A0C878",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
    marginTop: 4,
  },
  messageBubble: {
    maxWidth: "75%",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    marginVertical: 2,
  },
  userBubble: {
    backgroundColor: "#A0C878",
    borderBottomRightRadius: 4,
  },
  assistantBubble: {
    backgroundColor: "#F0F0F0",
    borderBottomLeftRadius: 4,
  },
  notesBubble: {
    backgroundColor: "#FFF8E1",
    borderBottomLeftRadius: 4,
    borderLeftWidth: 3,
    borderLeftColor: "#FF9800",
  },
  notesHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 8,
  },
  notesTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FF9800",
  },
  noteText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#333",
    marginBottom: 6,
  },
  saveNotesButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 12,
  },
  saveNotesButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  messageText: {
    fontSize: 16,
    lineHeight: 20,
  },
  userMessageText: {
    color: "#fff",
  },
  assistantMessageText: {
    color: "#333",
  },
  messageTime: {
    fontSize: 11,
    marginTop: 4,
  },
  userMessageTime: {
    color: "rgba(255,255,255,0.7)",
    textAlign: "right",
  },
  assistantMessageTime: {
    color: "rgba(0,0,0,0.5)",
  },
  typingBubble: {
    paddingVertical: 16,
  },
  typingIndicator: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#999",
  },
  inputContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 20,
    marginTop: "auto",
    marginBottom: 64,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "flex-end",
    borderRadius: 25,
    paddingHorizontal: 16,
    paddingVertical: 8,
    minHeight: 50,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  selectedImageContainer: {
    marginBottom: 8,
    position: "relative",
  },
  selectedImagePreview: {
    width: 100,
    height: 100,
    borderRadius: 12,
    marginHorizontal: 16,
  },
  removeImageButton: {
    position: "absolute",
    top: -8,
    right: 8,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 12,
  },
  imageButton: {
    padding: 8,
    marginRight: 4,
  },
  messageImage: {
    width: 200,
    height: 200,
    borderRadius: 12,
    marginBottom: 8,
  },
  diagnosisContainer: {
    backgroundColor: "rgba(76, 175, 80, 0.1)",
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#4CAF50",
  },
  diagnosisHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  diagnosisTitle: {
    fontWeight: "600",
    marginLeft: 6,
    fontSize: 14,
    color: "#4CAF50",
  },
  diagnosisText: {
    fontSize: 13,
    fontWeight: "500",
    color: "#333",
  },
  suggestionsContainer: {
    backgroundColor: "rgba(255, 152, 0, 0.1)",
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#FF9800",
  },
  suggestionsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  suggestionsTitle: {
    fontWeight: "600",
    marginLeft: 6,
    fontSize: 14,
    color: "#FF9800",
  },
  suggestionText: {
    fontSize: 13,
    fontWeight: "500",
    color: "#333",
    marginBottom: 4,
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    maxHeight: 100,
    paddingVertical: 8,
  },
  sendButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  waitingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  waitingAvatar: {
    width: 100,
    height: 100,
    marginBottom: 24,
    opacity: 0.6,
  },
  waitingText: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 8,
  },
  waitingSubtext: {
    fontSize: 14,
    textAlign: "center",
    opacity: 0.7,
  },
  newChatButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.1)",
  },
  newChatButtonText: {
    fontSize: 14,
    fontWeight: "500",
    marginLeft: 6,
  },
  buttonRow: {
    flexDirection: "row",
    marginTop: 8,
    gap: 8,
  },
  halfButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.1)",
  },
  halfButtonText: {
    fontSize: 13,
    fontWeight: "500",
    marginLeft: 6,
  },
  disabledButton: {
    opacity: 0.6,
  },
  historyButton: {
    // Özel stil eklenebilir
  },
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.1)",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "600",
  },
  closeButton: {
    padding: 4,
  },
  historyList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  historyItem: {
    flexDirection: "row",
    padding: 16,
    marginVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.1)",
  },
  historyItemContent: {
    flex: 1,
  },
  historyTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  historyDate: {
    fontSize: 12,
    opacity: 0.7,
    marginBottom: 4,
  },
  historyLastMessage: {
    fontSize: 14,
    opacity: 0.8,
  },
  historyItemActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  deleteButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255, 107, 107, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  historyItemRight: {
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 8,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 16,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    textAlign: "center",
    opacity: 0.7,
  },
  // Plant Selection Modal Styles
  plantsList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  plantSelectItem: {
    marginBottom: 12,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalSubtitle: {
    fontSize: 16,
    textAlign: "center",
    marginBottom: 20,
    paddingHorizontal: 16,
  },
  // Notes Bubble Styles
  notesBubble: {
    backgroundColor: "#E8F5E8",
    borderLeftWidth: 4,
    borderLeftColor: "#4CAF50",
    padding: 12,
    marginTop: 8,
  },
  notesHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  notesTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
    color: "#FF9800",
  },
  noteText: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 4,
    color: "#2E7D32",
  },
  saveNotesButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#4CAF50",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginTop: 12,
    alignSelf: "flex-start",
  },
  saveNotesButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 6,
  },
});
